### PR TITLE
Allow to configure a Serializer for Kafka

### PR DESCRIPTION
**Pull request by coreation**
## Notes

Hello everyone, first off, great job on making this such an active PHP project!
I'd like to use the Kafka queue, however my messages are encoded in Avro, which means I need to serialise them using a Schema registry. The only clean way without being intrusive, according to me, was to add a configuration entry called "serializer" and to capture this when setting up the RdKafkaContext.

If there are better ways of doing this, I'd love to hear them, if I need to alter some code or extra checks, i.e. check if the passes class exists before trying to instantiate it, let me know!

**UPDATE**
It was not my intention to edit the composer.json file, but it seems that the master version where I forked from has the requirement of needing "all" of the php extensions for all of the different queues this package supports.

I think I need some pointers on how to contribute best to this package, as the rdkafka is a read-only one.

### CODE REVIEW

**Comment by makasim** [comment]
It should be already possible to do. 

You must implement Serializer interface (https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/rdkafka/Serializer.php) and pass it to the context (https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/rdkafka/RdKafkaContext.php#L58).

**Comment by makasim** [comment]
I dont think that passing serializer in a config is a good idea. It should be set at runtime.

**Comment by coreation** [comment]
Thanks for the reply @makasim I'm using this in combination with the Enqueue Laravel package, how do you see this working "at runtime" exactly? The only way I see this being possible is to pass a serializer class path in the queue config. 

Am I correct to say that if I'd need this package, I would need to install all of the extensions (amqp, mongodb, ...) even though I just need one of the driver queues in this package?

**Comment by coreation** [comment]
> It should be already possible to do.
> 
> You must implement Serializer interface (https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/rdkafka/Serializer.php) and pass it to the context (https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/rdkafka/RdKafkaContext.php#L58).

I think in my PR that's what I'm doing, except for the fact that right now, it's being hard coded as a JsonSerializer, it first checks if it needs to use a different serializer. 

I just wanted to add that this PR isn't ready to be merged as I had to remove several dependencies of queue drivers that I don't need in my own branch. So if you could tell me how to handle that better (cfr. my previous comment), that'd be great! This package helped me save some work so anything I can do to contribute I'd be happy to.

**Pull request closed without merging**
