### PR TITLE
Remove unsupported Symfony versions

### PR DESCRIPTION
**Pull request by msheakoski**
Support for Symfony 3.0 ended in January 2017, and 3.2 ended in January 2018.

https://symfony.com/doc/current/contributing/community/releases.html#schedule

### CODE REVIEW

**Comment by makasim** [comment]
Then we have to raise the minimum symfony version too in composer.json.

I am fine setting it to `^3.4` but maybe starting from 0.9

**Comment by msheakoski** [comment]
That is a good point. I forgot about composer.json. I agree with you about waiting until 0.9 since it would be a breaking change. 3.3 will also be end of life on 07/2018 so skipping directly to ^3.4 makes sense. Should I close this PR and make a new one on the 0.9 branch?

**Comment by makasim** [comment]
You can try to change the base of the pull request, most of the time it works out.

**Comment by msheakoski** [comment]
I'm not sure what happened here. I may have triggered GitHub to close it when I was messing around with my fork through git. I will re-open this PR based on the recently merged changes in the 0.9 branch.

**Comment by makasim** [comment]
👍

**Pull request closed without merging**
