### PR TITLE
Allow psr/container v2

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
@makasim Could you review this please?

**Comment by makasim** [comment]
could you sync with the latest master branch ? there are some fixes for the tests. Would be good to merge it once it green

**Comment by ADmad** [comment]
> could you sync with the latest master branch ?

Done

**Comment by ADmad** [comment]
Ping

**Comment by makasim** [comment]
There is a failed CI job

**Comment by ADmad** [comment]
Well I have no idea how this change could be affecting that test. Can you just try re-running the testsuite? Could a flaky test or an issue with the CI environment.

**Comment by makasim** [comment]
I've tried, no luck.

**Comment by othercorey** [comment]
This is the failure. Does it look familiar to you?

```
1) Enqueue\Dbal\Tests\Spec\Mysql\DbalSubscriptionConsumerConsumeFromAllSubscribedQueuesTest::test
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'fooBody'
-    1 => 'barBody'
 )
```

**Comment by othercorey** [comment]
@makasim We cannot find any connection to the changes in psr/container v2 for this test. I'm not sure what you expect us to do to resolve this. Can we run the tests again?

**Comment by makasim** [comment]
re-run it. it might very well be not related to your changes. thought CI must be green before I can merge otherwise it would soon go out of control.

**Comment by othercorey** [comment]
> I re-run the tests. it might very well be not related to your changes. though CI must be green before I can merge otherwise it would soon go out of control.

We appreciate that need. I had a hard time following that specific test so I wasn't sure how to help.

**Comment by makasim** [comment]
That's indeed a wired one. Recently there was a PR https://github.com/php-enqueue/enqueue-dev/pull/1211 that addressed issues with the tests. And it was green.

**Comment by othercorey** [comment]
This appears to pass now. Hope that's enough.

**Pull request merged**
