### PR TITLE
fix: require only released own packages

### LINKED ISSUE #788: [All] Released packaged should only require other released packages
Currently in the 0.9 branch, a lot of packages require `dev` versions of other packages, examples:

https://github.com/php-enqueue/enqueue-dev/blob/7ab383fe6ef0239132d0f9ec72d1beb74aaf1374/pkg/amqp-bunny/composer.json#L12

https://github.com/php-enqueue/enqueue-dev/blob/7ab383fe6ef0239132d0f9ec72d1beb74aaf1374/pkg/amqp-ext/composer.json#L12

https://github.com/php-enqueue/enqueue-dev/blob/7ab383fe6ef0239132d0f9ec72d1beb74aaf1374/pkg/amqp-lib/composer.json#L12

etc. This doesn't allow to install all the packages' release versions but instead, need to install some of them as git clones.

### PR DESCRIPTION
**Pull request by dkarlovi**
Closes #788.

### CODE REVIEW

**Comment by dkarlovi** [comment]
Failures unrelated, it seems.

**Comment by makasim** [comment]
Could you open it against master? 0.9 branch is stale

**Comment by dkarlovi** [comment]
@makasim not sure I understand, do you not release 0.9.x from `0.9` and do development for 0.10 in `master`?

**Comment by makasim** [comment]
master is 0.9, there is no work on 0.10 version.

**Comment by dkarlovi** [comment]
Got it, I'll rebase to master tomorrow.

**Comment by dkarlovi** [comment]
Not required, master is already correct.

**Pull request closed without merging**
