### PR TITLE
Fix ping to check each connection, not only first one

### PR DESCRIPTION
**Pull request by webmake**

### CODE REVIEW

**Comment by makasim** [comment]
@webmake could you change the base branch to 0.8. It would be good to have it fixed there too.

**Comment by webmake** [comment]
It seems random test failure:
```
1) Enqueue\Dbal\Tests\Functional\DbalConsumerTest::testShouldOrderMessagesWithSamePriorityByPublishedAtDate
InvalidArgumentException: $bytes string should contain 16 characters.
2) Enqueue\SimpleClient\Tests\Functional\SimpleClientTest::testSendEventWithTwoSubscriber with data set "dbal_dsn" (array('mysql://root:rootpass@mysql/mqdev'), '+1sec')
InvalidArgumentException: $bytes string should contain 16 characters.
```
not related with a change

**Comment by makasim** [comment]
@webmake yeap.

**Comment by makasim** [comment]
@webmake it added to much an related changes to the PR (because of base branch change). Would it be possible to cherry-pick your commit to a new PR with 0.8 as a base?

**Comment by webmake** [comment]
Yeah, i see. Okay

**Pull request closed without merging**
