### PR TITLE
[amqp-tools] Allow for using vhost='/'

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by makasim** [comment]
This is the right syntax for `/` as vhost: `amqp://host/%2f`. More here https://www.rabbitmq.com/uri-spec.html

**Comment by Nyholm** [comment]
Okey. So if I configure my dns like ‘amqp://host/%2f’ then I would be all fine. Thanks. 

So my PR is basically just syntactic sugar to improve DX for other people like me that does not know about %2f.

**Comment by makasim** [comment]
> So my PR is basically just syntactic sugar to improve DX for other people like me that does not know about %2f.

The RabbitMQ doc says that `amqp://host/` should have empty string vhost.

**Comment by Nyholm** [comment]
Fair. But when I configured my DSN like `ampq://foo:bar@host:port/`, I've got a complaint that "vhost cannot be empty". (Using Bunny adapter)

**Comment by makasim** [comment]
Sorry, Couldn't be merged cuz it contradicts RabbitMQ doc.

**Comment by Nyholm** [comment]
I understand. Thank you for the review

**Pull request closed without merging**
