### PR TITLE
Issue-455: fix RabbitMqDelayPluginDelayStrategy for RabbitmMQ 3.7.5 version

### PR DESCRIPTION
**Pull request by scarbo87**
`RabbitMqDelayPluginDelayStrategy`: options x-delay must be header, not the property

https://github.com/php-enqueue/enqueue-dev/issues/455

### CODE REVIEW

**Comment by makasim** [comment]
@scarbo87  Have you tested it? I am sure we've tested it and it worked

**Comment by makasim** [comment]
@scarbo87  Is there a link I can read more about the change?

**Comment by makasim** [comment]
> Can I make a new RabbitMq375DelayPluginDelayStrategy?

@scarbo87 that would be great

**Comment by scarbo87** [comment]
> @scarbo87 that would be great

@makasim, can I update the docker rabbitmq image?

**Comment by makasim** [comment]
you could add another one with 3.7 version in it. and force 3.6 for current one.

**Comment by scarbo87** [comment]
@makasim, added `RabbitMq375DelayPluginDelayStrategy `

**Comment by makasim** [comment]
@scarbo87 I've updated rabbitmq image to 3.7 with a delay plugin and the current implementation of delay plugin works, at least tests are passing. 

see https://github.com/php-enqueue/enqueue-dev/pull/506

closing it for now, feel free to reopen if you have some additional info or steps to reproduce the issue.

**Pull request closed without merging**
