### PR TITLE
Add PHP 8.1 and 8.2, Symfony 6.2 to CI

### PR DESCRIPTION
**Pull request by andrewmy**
- Add PHP 8.1 and PHP 8.2, Symfony 6.2 to the CI
- Drop PHP 7.3, Symfony < 5.4 and < 6.2 as they all are EOL
- Remove the `rdkafka` test group
- Introduce the `gearman` test group and skip it on PHP 8.1 — see https://github.com/php/pecl-networking-gearman/issues/16 — the issue is fixed on master but needs a release

### CODE REVIEW

**Comment by andrewmy** [comment]
@makasim could you please publish the new docker tags? I guess that means just running https://github.com/makasim/docker-nginx-php-fpm/blob/master/8.1/push-images.sh

**Comment by makasim** [comment]
Thanks, pushed new versions:
```
docker push makasim/nginx-php-fpm:8.1
docker push makasim/nginx-php-fpm:8.1-all-exts
docker push makasim/nginx-php-fpm:8.2
docker push makasim/nginx-php-fpm:8.2-all-exts
docker push makasim/nginx-php-fpm:latest
```

**Comment by andrewmy** [comment]
> The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

@makasim please rebuild all images for linux/amd64, and congrats on getting an ARM Mac :)
See https://github.com/makasim/docker-nginx-php-fpm/pull/8

**Comment by andrewmy** [comment]
@makasim could you please rebuild and retag the docker images? 🙏

**Comment by makasim** [comment]
Took me some time to make it work. Ive pushed 7.4 and will do the rest over weekends. 

Screenshot 2023-03-18 at 11 09 25

**Comment by makasim** [comment]
@andrewmy images have been updated

**Comment by andrewmy** [comment]
Okay it's ready 😅 @makasim

**Comment by makasim** [comment]
Thank you!

**Pull request merged**
