### PR TITLE
Fix types for Symfony 5.4

### PR DESCRIPTION
**Pull request by shyim**
image

### CODE REVIEW

**Comment by ruudk** [comment]
@shyim Thanks for this. Could you please also fix the code style issue?

**Comment by shyim** [comment]
@ruudk done

**Comment by ruudk** [comment]
@makasim Could you approve the workflow so that we can see if it passes?

**Comment by shyim** [comment]
@ruudk I guess the failing one fails also in master

**Comment by ruudk** [comment]
@makasim What do you think, can this be merged?

**Comment by shyim** [comment]
Can we have this released, so we can get rid of that error?

**Pull request merged**
