### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ruudk**
Let's see if CI passes here.

### CODE REVIEW

**Comment by ruudk** [comment]
@makasim Please approve the workflow.

**Comment by ruudk** [comment]
Surprise, all the tests fail.

**Comment by makasim** [comment]
I do not use this project nor I use PHP. I am not going to spend my time fixing it. I have zero interest in it. 

I still maintain the project if PR is well prepared and CI passes. Sorry, that's the only way I can keep it going.

**Comment by ruudk** [comment]
Thanks for explaining it. I understand.

Is @ASKozienko still using PHP and willing to maintain it?

If not, would it be an idea to mark this package as `abandoned` on Packagist to hint people to use something else?

**Comment by makasim** [comment]
It is not abandoned. There are contributions and releases.

**Comment by makasim** [comment]
> Is @ASKozienko still using PHP and willing to maintain it?

I doubt he would do it.

**Pull request closed without merging**
