### PR TITLE
Remove bool typehint for php < 7 supports

### PR DESCRIPTION
**Pull request by ArnaudTarroux**
Remove bool typehint for php < 7 supports

### CODE REVIEW

**Comment by andipohl** [comment]
@makasim Please create a composer-version with this changes. We use the enqueue-lib on php56 and have the issue addressed with this fix

**Comment by makasim** [comment]
@andipohl tagged 0.8.36. It should contain this fix. Please check

https://github.com/php-enqueue/enqueue/releases/tag/0.8.36

**Comment by andipohl** [comment]
Thanks!

**Comment by bendavies** [comment]
Errr, there's a bug here. you've removed the setter completely!

**Comment by ArnaudTarroux** [comment]
I'm sorry, I don't know what's happened in my head. fixed here #541

**Pull request merged**
