### PR TITLE
Sqs decorator friendly

### PR DESCRIPTION
**Pull request by kbsali**

### CODE REVIEW

**Comment by makasim** [comment]
@kbsali what is the problem you are trying to solve?

**Comment by kbsali** [comment]
I need to use a custom `SqsContext` (decorating the Enqueue one) so I can overwrite the `getQueueUrl()`; but `SqsProducer` has a hard dependency with `Enqueue\Sqs`SqsContext`... my `getQueueUrl()` is therefore never called.
(This a Symfony integration)

**Comment by makasim** [comment]
@kbsali Could you tell what you've changed in getQueueUrl()?

**Comment by makasim** [comment]
@kbsali could you post the changes you are doing so I can think of a better approach

**Comment by makasim** [comment]
@kbsali If you could overwrite only a factory, would it help you to solve your issue? A new bundle version allows to configure `connection_factory` class.

```yaml
enqueue:
  transport:
    dsn: '%env(ENQUEUE_DSN)%'
    connection_factory_class: 'Your/Custom/ConnectionFactory'
```

**Comment by kbsali** [comment]
sorry, i'll close this PR as i'm not sure how to make it "the way you'd like" :)
We have finally managed to migrate all our queues from Redis to SQS,
but the problem remains : right now it is not possible, as far as I could see, to manage several queues with different brokers!

**Comment by makasim** [comment]
@kbsali could you post the code you currently use, a workaround.

**Pull request closed without merging**
