### PR TITLE
Added support for ramsey/uuid 4.0

### PR DESCRIPTION
**Pull request by a-menshchikov**

### CODE REVIEW

**Comment by snapshotpl** [comment]
@makasim can you release this change?

**Comment by makasim** [comment]
this PR updates only root composer.json but the version has to be updated in all packages.

**Comment by levelfivehub** [comment]
Does this mean, it is best to remain with ramsey/uuid 3 until further notice?

**Comment by atrauzzi** [comment]
Is there any chance we can get this fix released?  It's making installation very difficult...

**Pull request merged**
