### PR TITLE
Fix partition's choice for the cases when partition number is zero

### PR DESCRIPTION
**Pull request by rodrigosarmentopicpay**

### CODE REVIEW

**Comment by makasim** [comment]
could you add a test forthis case ?

**Comment by rodrigosarmentopicpay** [comment]
> could you add a test forthis case ?

Ok, I will do it.

**Comment by rodrigosarmentopicpay** [comment]
> could you add a test forthis case ?

The tests are included as requested.

**Comment by rodrigosarmentopicpay** [comment]
Hi Max, is there anything missing? The error seems to be related to the rabbitmq repo, not to my changes.

**Comment by makasim** [comment]
It is, yes.  But unfortunately  I can merge only green PR. So the issue has to be addressed.

**Comment by rodrigosarmentopicpay** [comment]
> It is, yes. But unfortunately I can merge only green PR. So the issue has to be addressed.

Ok, now it's all ok!

**Comment by makasim** [comment]
@rodrigosarmentopicpay thank you, merged

**Pull request merged**
