### PR TITLE
Update doctrine/persistence

### PR DESCRIPTION
**Pull request by jlabedo**
Update doctrine/persistence to ^3.0

### CODE REVIEW

**Comment by makasim** [comment]
I think it is too much to support three major versions at the same time. 

Could you drop 1.x version  ? It was updated about two years ago last time.

**Comment by xNarkon** [comment]
Any update on this?

**Comment by makasim** [comment]
>I can handle this topic if the original owner is out

@xNarkon that would be great

**Comment by xNarkon** [comment]
@makasim https://github.com/php-enqueue/enqueue-dev/pull/1300

**Comment by dgafka** [comment]
Hey :)

@jlabedo can we drop the version `1` and push it forward?

**Comment by jlabedo** [comment]
Sorry for the delay @makasim, the branch is updated. I was super busy at work on a new project that uses enqueue and ecotone framework :)

**Comment by jlabedo** [comment]
@makasim , I think this PR could still be needed even after merging #1300 :
1. It allows doctrine/persistence 3.0 and not only 3.1
2. It make ci test against the latest ^3.0: as it is not updated in enqueue-dev root composer.json, the ci is still going on ^2.0 😄  (see: https://github.com/php-enqueue/enqueue-dev/actions/runs/4884813943/jobs/8857137748?pr=1300#step:7:39)

**Pull request merged**
