### PR TITLE
Add PHP8 to CI builds

### PR DESCRIPTION
**Pull request by markstory**
Trying to get PHP8 compatibility started. This is likely wrong and broken, but need to start somewhere.

Refs #1108

### CODE REVIEW

**Comment by svbackend** [comment]
Hello guys, could someone explain me the process of migration to php8? As far as I understand the main problem is phpunit update (from v7 to v9) as it's not backward compatible? So this enqueue package in order to support php8 should have a new branch with different php version requirements I suppose? Is there any branch where I can join to help migrate to php8? Because I just cloned this repository, but I can't just add a php^8 to composer.json and update travis.yml as all previous builds will fail because of new phpunit version (as you can see in this pull request).

Would be really nice to have some guidance/roadmap from maintainers with list of steps to accomplish in order to migrate to php8, I see it like this:
1. Create new branch for next major version of enqueue with php8 support
2. In this new branch travis.yml should be cleaned up, remove every php^7 build from there and add only new php8 builds 
3. Update tests to be compatible with phpunit 9
4. Update whole codebase, need to rename all newly reserved words (e.g class with name Match not longer allowed in php8, ref: https://github.com/sebastianbergmann/phpunit/issues/4533) 
5. ...
6. Profit!

is this sounds as a plan or am I missing something?

**Comment by Steveb-p** [comment]
@svbackend in general yes, it boils down to updating phpunit dependency and checking if the codebase of library itself doesn't have any issues with PHP8 syntax.

One point I need to make though - this library will still need to maintain PHP7 compatibility for some time, at least until PHP 7.4 reaches it's end of life I suppose. This pretty much means that PHP8-specific syntax should not be used, as it will break compatibility with PHP7.

**Comment by svbackend** [comment]
@Steveb-p ok, thanks, sounds clear, I will create a new PR within a week to get process started

**Comment by Jurigag** [comment]
Anyone plans to do something here? It seems to me this PR died.

**Comment by svbackend** [comment]
@Jurigag Yep, I'm working on it in different PR: 
https://github.com/php-enqueue/enqueue-dev/pull/1121

Hopefully to finish by the end of January, meanwhile I'm already using enqueue with redis on php 8, seems like it's working fine

**Comment by Jurigag** [comment]
Then i think this PR could be closed then?

**Comment by svbackend** [comment]
> Then i think this PR could be closed then?

I guess so

> Are you planning to also update related repos like https://github.com/php-enqueue/sns ?

It's monorepo, as far as I understand my changes here would be automatically applied to all other repositories for specific transports, so yes, sns also in that list

**Comment by markstory** [comment]
I can close this given that #1121 is progressing better. I haven't had much time to dedicate to this sorry.

**Pull request closed without merging**
