### PR TITLE
update symfony version to v7

### PR DESCRIPTION
**Pull request by Rastusik**
Support for Symfony 7 like https://github.com/php-enqueue/enqueue-bundle/pull/8 but hopefully with fixed CI problems (duplicate from https://github.com/php-enqueue/enqueue-bundle/pull/12)

### CODE REVIEW

**Comment by igordeveloper** [comment]
Any news about this PR?
Need some fix to release for SF7 support?

thank you!

**Comment by Rastusik** [comment]
I currently don't have much time to address this. Any help with failing tests would be much appreciated!

**Comment by makasim** [comment]
I dont mind. we can keep current and prev versions both symfony and php. Drop everything older.

**Comment by igordeveloper** [comment]
> I dont mind. we can keep current and prev versions both symfony and php. Drop everything older.

Thank you for the feedback.
Currently,do you know if there a team working with this update or the project need PR's?

**Comment by makasim** [comment]
No idea.

**Comment by igordeveloper** [comment]
> No idea.
If you have no idea, I have no idea either.
The problem that SF7 is released one year ago and we have no way to use the packages.

**Comment by makasim** [comment]
I've used PHP\Symfony last time in 2018. I am here only for you guys. If you contribute something, I'll merge and release it. That's the maximum I can offer. 

You can take it, or leave it. You have that choice.

**Comment by igordeveloper** [comment]
> I've used PHP\Symfony last time in 2018. I am here only for you guys. If you contribute something, I'll merge and release it. That's the maximum I can offer.
> 
> You can take it, or leave it. You have that choice.

thank you!

**Comment by igordeveloper** [comment]
> I've used PHP\Symfony last time in 2018. I am here only for you guys. If you contribute something, I'll merge and release it. That's the maximum I can offer.
> 
> You can take it, or leave it. You have that choice.

I will leave it, thank you

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/pull/1362

**Pull request closed without merging**
