### PR TITLE
PHP_URL_SCHEME doesn't support underscores

### PR DESCRIPTION
**Pull request by coudenysj**
https://github.com/php-enqueue/dbal/pull/2

### CODE REVIEW

**Comment by coudenysj** [comment]
Is it ok if I replace it with a regex check?

**Comment by makasim** [comment]
> Is it ok if I replace it with a regex check?

what exactly?

**Comment by makasim** [comment]
@coudenysj ping

**Comment by coudenysj** [comment]
The following line (parse_url) doesn't support underscores:

https://github.com/php-enqueue/enqueue-dev/blob/9cea3918ee88d0156d5bb9c60cef490289036498/pkg/dbal/DbalConnectionFactory.php#L101

So only a subset of this list is actually supported:

https://github.com/php-enqueue/enqueue-dev/blob/9cea3918ee88d0156d5bb9c60cef490289036498/pkg/dbal/DbalConnectionFactory.php#L106-L121

**Comment by coudenysj** [comment]
Here you go.

**Comment by coudenysj** [comment]
Could you re-run the checks? I didn't change anything to the MongoDB testCouldBeConstructedWithCustomConfiguration.

**Comment by makasim** [comment]
@coudenysj Mongodb failed test is not related to your changes. I am aware of it.

**Pull request merged**
