### PR TITLE
Better Symfony doc nav

### PR DESCRIPTION
**Pull request by sylfabre**
Actually there is a lot of documentation for Symfony but it's not easy to navigate through the pages as the links always get you back to the general doc instead of a Symfony homepage

### CODE REVIEW

**Comment by makasim** [comment]
Do the changes still make sense after gh-pages introduction: https://php-enqueue.github.io/ ?

**Comment by Steveb-p** [comment]
> Do the changes still make sense after gh-pages introduction: https://php-enqueue.github.io/ ?

@makasim Kinda still yes. Internal bundle docs should still only go one level up instead of going to top level index.md.

Introducing index.md however is no longer necessary, since it already auto-generates table of contents now. I believe it's also why conflict is reported.

**Comment by makasim** [comment]
@sylfabre could you please resolve conflicts?

**Comment by Steveb-p** [comment]
@makasim Aren't they already resolved now? I used the magic "resolve conflicts" on github and went through looking what should go where... :)

**Comment by makasim** [comment]
> Aren't they already resolved now? I used the magic "resolve conflicts" on github and went through looking what should go where... :)

I always forget about that feature (:

**Pull request merged**
