### PR TITLE
Allow symfony 5

### PR DESCRIPTION
**Pull request by Jeroeny**
#SymfonyHackday

### CODE REVIEW

**Comment by Steveb-p** [comment]
We should also add 5.0 to travis matrix.

**Comment by Jeroeny** [comment]
> We should also add 5.0 to travis matrix.

Added, let me know what you think 👍.

**Comment by Steveb-p** [comment]
The are some conflicts with dev dependencies.

There should also be an expected test failure due to #984 not yet resolved :)

**Comment by Jeroeny** [comment]
> The are some conflicts with dev dependencies.
> 
> There should also be an expected test failure due to #984 not yet resolved :)
> 
> I’ll have a look once I’m in front of a pc.

Indeed, it's this package: https://github.com/voryx/Thruway/pull/329, for which I've made a PR.
Also PhpStan, but it looks like they already have a version WIP that removes a lot of dependencies, including symfony.

**Comment by kuraobi** [comment]
@Jeroeny your PR was not sufficient so I did another one: https://github.com/voryx/Thruway/pull/331 , but the maintainer says he prefers to remove the dependency to Symfony. So waiting for him to fork https://github.com/symfony/event-dispatcher and use that fork instead.

**Comment by kuraobi** [comment]
As there was no activity on voryx/Thruway#331 , I found another solution in #997 . Actually had a lot more to fix then, I detailed it in my PR.

**Pull request merged**
