### PR TITLE
Automatically enable traceable producer depends on debug

### PR DESCRIPTION
**Pull request by Koc**
Make same behavior like in all other bundles.

TODO:
- [ ] fix tests

### CODE REVIEW

**Comment by makasim** [comment]
wouldn't it be better to do it on an app or a recipe level like this?

```yml
enqueue
   client: 
     traceable_producer: %kernel.debug%
```

**Comment by Koc** [comment]
you can do this also or use any other parameter what you want. But for zero-line configuration better using suggested approach. It widely used already in many bundles, like: [DoctrineBundle](https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Configuration.php#L25), [SncRedisBundle](https://github.com/snc/SncRedisBundle/blob/master/DependencyInjection/Configuration/Configuration.php#L27) and many other

**Comment by Koc** [comment]
Even more, this approach suggested by Symfony: http://symfony.com/doc/current/configuration/using_parameters_in_dic.html

Only one thing: did you know why `testShouldConfigureFooTransport` fails?

**Comment by makasim** [comment]
@Koc ok let's do it then.  I don't know why it fails.

**Comment by makasim** [comment]
merged

**Comment by Koc** [comment]
@makasim thank you. Have you fixed tests? I've tryed but cann't

**Comment by makasim** [comment]
@Koc sure, they are fixed

**Pull request closed without merging**
