### PR TITLE
Add PHP 8

### LINKED ISSUE #1108: PHP 8 Support?
With PHP 8 coming out soon, I was wondering if you had started thinking about adding PHP8 to your CI matrix and composer constraint?

I'm happy to help with that process and can get it started, but I'm not familiar with all of the transports that enqueue supports and would likely require assistance to get everything working.

### LINKED ISSUE #1123: Conflict between symfony/cache and php-enqueue/job-queue
https://github.com/php-enqueue/job-queue/blob/master/composer.json#L14
https://github.com/symfony/cache/blob/5.x/composer.json#L35

изображение

### PR DESCRIPTION
**Pull request by andrewmy**
Currently blocked by:
- [ ] https://github.com/richardfullmer/php-rabbitmq-management-api/pull/11 — green, waiting for merge, using a fork for testing.
- [x] https://github.com/doctrine/DoctrineMongoDBBundle/pull/662 ~or https://github.com/doctrine/DoctrineMongoDBBundle/pull/665~ — ~almost~ green 😬 ~using a fork for testing~ v4.3 🎉
- [x] https://github.com/formapro/docker-nginx-php-fpm/pull/6 or https://github.com/makasim/docker-nginx-php-fpm/pull/2 — green
- [x] https://github.com/stomp-php/stomp-php/pull/157 — green ~, waiting for merge, using a fork for testing~ v5 🎉;
  - originally not tested even on 7.4 😬 the latest is 4.6.1 (`php: ^7.0`); CI installs 4.2.2 as it has an open PHP version constraint (`>=5.5.0`) 😂 
- [x] a `7.3` tag for the docker image :D https://github.com/makasim/docker-nginx-php-fpm/pull/2#issuecomment-766823344

Notes:
- ~ODM bundle v4.3.x won't work with Symfony 4.3, not sure if affects anyone once we can specify `^3.5|^4.3` for the bundle again~ all g
- Not sure how to handle enqueue/dev docker image pushing, building from ~formapro~ makasim base atm

Fixes #1108
Fixes #1123

### CODE REVIEW

**Comment by andrewmy** [comment]
Mkay all green now, just waiting for a merge and release from https://github.com/richardfullmer/php-rabbitmq-management-api/pull/11

If a week more goes by, maybe we could switch to a fork?

**Comment by makasim** [comment]
I am fine with a fork and a comment on why it was needed.

**Comment by andrewmy** [comment]
I've tagged a release of php-rabbitmq-management-api in my fork. Since I expect the original author to respond in observable future, I chose the temporary fork route, not publishing the fork on packagist.

Where do I put the comment you mentioned @makasim?

Else this appears to be ready to roll 🚀

**Review by makasim — APPROVED** [review]

**Comment by makasim** [comment]
I've tagged 0.10.8. @andrewmy big thank you for your work. Don't you mind my mentioning you on twitter ? Do you have one ?

**Comment by andrewmy** [comment]
Thanks for the merge! I'm @andr on Twitter ☺️

**Comment by andrewmy** [comment]
@makasim can't see neither the new tag nor release here 😅

**Comment by makasim** [comment]
yeap, false alarm. the script failed.

**Comment by makasim** [comment]
```
++ ./bin/splitsh-lite --prefix=pkg/amqp-lib
0 commits created, 0 commits traversed, in 0s
+ SHA1=e9b77b8ab49cd30e18347250f67323a066060fcd
+ git push amqp-lib e9b77b8ab49cd30e18347250f67323a066060fcd:refs/heads/master
ssh_dispatch_run_fatal: Connection to 140.82.121.3 port 22: Operation timed out
fatal: Could not read from remote repository.
```

not sure what is going on there, the `bin/subtree-split.sh` command has been working for ages.

**Comment by Jurigag** [comment]
@makasim where exactly is this 0.10.8 tagged? Doesn't see it on github anywhere.

**Comment by makasim** [comment]
Now, all is good

**Pull request merged**
