### PR TITLE
Add header support for Symfony's produce command

### LINKED ISSUE #963: Add options to send headers with enqueue:produce command
There is currently no possibility to send headers with the  `enqueue:produce` command. It would be nice to add an option to specify headers:

```
$ bin/console enqueue:produce '{"foo": "message content"}' --topic=... --header='Content-Type: application/json' --header='Action: create' 
```

### PR DESCRIPTION
**Pull request by TiMESPLiNTER**
Fixes #963

### CODE REVIEW

**Comment by Steveb-p** [comment]
@TiMESPLiNTER You can check local test run script instructions here https://github.com/php-enqueue/enqueue-dev/blob/master/docs/contribution.md (kinda obscure, that's why I'm linking it in case you've missed it)

**Comment by Steveb-p** [comment]
Looks good to me. I've double checked that `SimpleClient` does indeed automatically convert string messages into `Message` instance.

**Comment by Steveb-p** [comment]
@makasim Looks simple enough to me. Could I merge PR's like this in the future in case you're occupied or you'd like to keep control over it?

**Comment by makasim** [comment]
@Steveb-p sure, I don't mind

**Pull request merged**
