### PR TITLE
Add php 7.4 to test matrix

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by Steveb-p** [comment]
Isn't PHP 7.4 now officially out? `snapshot` prefix should soon not be required, if it isn't already in Travis.

**Comment by ruudk** [comment]
Unstale

**Comment by ruudk** [comment]
Unstale 🤦‍♂

**Comment by Steveb-p** [comment]
I've re-run the tests.

Apparently some tests are failing on PHP 7.4 specifically:

```diff
There were 2 errors:
1) Enqueue\Pheanstalk\Tests\PheanstalkConsumerTest::testShouldReceiveFromQueueAndReturnMessageIfMessageInQueue
Trying to access array offset on value of type null
/home/travis/build/php-enqueue/enqueue-dev/pkg/pheanstalk/PheanstalkConsumer.php:114
/home/travis/build/php-enqueue/enqueue-dev/pkg/pheanstalk/PheanstalkConsumer.php:53
/home/travis/build/php-enqueue/enqueue-dev/pkg/pheanstalk/Tests/PheanstalkConsumerTest.php:71
2) Enqueue\Pheanstalk\Tests\PheanstalkConsumerTest::testShouldReceiveNoWaitFromQueueAndReturnMessageIfMessageInQueue
Trying to access array offset on value of type null
/home/travis/build/php-enqueue/enqueue-dev/pkg/pheanstalk/PheanstalkConsumer.php:114
/home/travis/build/php-enqueue/enqueue-dev/pkg/pheanstalk/PheanstalkConsumer.php:66
/home/travis/build/php-enqueue/enqueue-dev/pkg/pheanstalk/Tests/PheanstalkConsumerTest.php:113
```

We'll have to fix them before merging.

**Comment by snapshotpl** [comment]
@Steveb-p all test green!

**Comment by makasim** [comment]
It contains some unrelated changes.

 I am gonna merge this for now but please open separate PRs in future.

**Pull request merged**
