### PR TITLE
[dbal] Use string-based UUIDs instead of binary

### PR DESCRIPTION
**Pull request by jverdeyen**
Fixes issues #670

### CODE REVIEW

**Comment by sixdayz** [comment]
I'm really looking forward to this change

**Comment by jverdeyen** [comment]
I'll fix the tests asap! Feel free to contribute.

**Comment by makasim** [comment]
@jverdeyen I fixed tests.

**Comment by jverdeyen** [comment]
> @jverdeyen I fixed tests.

💪 Hero!

**Pull request merged**
