### PR TITLE
Fix Incompatibility for doctrine

### PR DESCRIPTION
**Pull request by Baachi**
Hey guys,

i adjusted the code from #985 and added a test for this class.

#SymfonyHackday

### CODE REVIEW

**Comment by rogamoore** [comment]
👍 Anything preventing from merging and releasing this fix? :)

**Comment by Steveb-p** [comment]
@rogamoore I'm usually not the one merging, since I've opted to take care Kafka part of Enqueue, but it seems @makasim is recently pretty busy.

I'll let it "bake" for some time, in case someone has any additional comments (like I've made the assumption that previous PR doing this is OK while it was pointing to wrong class, so I don't want to hastily merge).

At the same time, you can use Composer's functionality to overwrite packages to temporarily provide your own fork instead of a package: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

> Loading a package from a VCS repository
There are a few use cases for this. The most common one is maintaining your own fork of a third party library. If you are using a certain library for your project and you decide to change something in the library, you will want your project to use the patched version. If the library is on GitHub (this is the case most of the time), you can simply fork it there and push your changes to your fork. After that you update the project's composer.json. All you have to do is add your fork as a repository and update the version constraint to point to your custom branch. In composer.json, you should prefix your custom branch name with "dev-".

**Comment by makasim** [comment]
It looks good. One thing though: Doctrine version has to be updated in composer.json. 

@Steveb-p I don't use the library nor work with PHP these days. Feel free to take over it (if you have that desire of course).

**Comment by Steveb-p** [comment]
@makasim I can take it over if you're not working with it anymore. As we discussed in another issue (the one where you were looking for maintainers) I'll keep directly maintaining only the part with Kafka, since that's the package I'm familiar with, but will take a little more active approach with PR's from other packages.

I'll check/review this PR in more detail tonight after work @rogamoore

**Comment by makasim** [comment]
Thank you @Steveb-p

**Comment by rogamoore** [comment]
Regarding the Doctrine version I think this fix is still compatible with Doctrine Bundle <2.0 because it's just an alias that was removed, so using the `Doctrine\Common\Persistence\ManagerRegistry` directly should have been possible already before.

**Comment by alcaeus** [comment]
> Regarding the Doctrine version I think this fix is still compatible with Doctrine Bundle <2.0 because it's just an alias that was removed, so using the `Doctrine\Common\Persistence\ManagerRegistry` directly should have been possible already before.

That is correct - this uses the base interface for all manager registries.

**Pull request merged**
