### PR TITLE
issue #367 - pass options to predis client

### PR DESCRIPTION
**Pull request by fvaresi**
#367

### CODE REVIEW

**Comment by makasim** [comment]
It would be better to upgrade the constructor of RedisConnectionFactory so that it accepts an instance of [Redis](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/redis/Redis.php) object.

**Comment by fvaresi** [comment]
@makasim ok, will give that a try.

**Comment by fvaresi** [comment]
Hi @makasim. I was reviewing the code and I think handling this as a config option is better than modifying the constructor of RedisConnectionFactory for the following reasons:

a) if we modify RedisConnectionFactory, we won't be able to continue using the RedisTransportFactory abstraction without significant modifications.
b) one could still use RedisConnectionFactory directly, but this would make it difficult to switch to a different transport in the future
c) if we use the proposed changes in config handling instead, SimpleClient would still work without any changes.

What do you think? Do you still think modifying RedisConnectionFactory is the best option?

**Comment by makasim** [comment]
there is a better solution https://github.com/php-enqueue/enqueue-dev/issues/367#issuecomment-365867762

**Pull request closed without merging**
