### PR TITLE
add symfony 7 support for enqueue-bundle

### PR DESCRIPTION
**Pull request by zavitkov**
Extending of https://github.com/php-enqueue/enqueue-dev/pull/1356 with removing php 7.4 and 8.0 and symfony <=6.2 support.
We can remove these versions support as AWS officially stop supporting php <= 8.1: https://aws.amazon.com/ru/blogs/developer/announcing-the-end-of-support-for-php-runtimes-8-0-x-and-below-in-the-aws-sdk-for-php/.

Some symfony deprecations are fixed as well

### CODE REVIEW

**Comment by y0rker** [comment]
Hello! Very important to merge

**Comment by zavitkov** [comment]
@makasim Hi. Could you please run the pipeline?
Thanks in advance:)

**Comment by zavitkov** [comment]
@makasim Thanks! What’s next?

**Comment by makasim** [comment]
Merged. I've synced subtree repos. I am going to keep it that way for a week or two so everybody can test it and provide feedback. If everything is fine I'll tag it.

**Comment by makasim** [comment]
Thanks.

**Comment by zavitkov** [comment]
Perfect! Thanks.

**Comment by andrewmy** [comment]
nice, this one didn't have problems with localstack as mine did :D

**Comment by Steveb-p** [comment]
> nice, this one didn't have problems with localstack as mine did :D

https://github.com/php-enqueue/enqueue-dev/pull/1349 dealt with this in meantime. That's why :sweat_smile:

**Comment by zavitkov** [comment]
@makasim Hi! Maybe it's time for a new tag?:)

**Comment by makasim** [comment]
Tagged 0.10.24

**Pull request merged**
