### PR TITLE
Fix DoctrineConnectionFactoryFactory due to doctrine/common changes

### LINKED ISSUE #1085: Type mismatch in DoctrineConnectionFactoryFactory
Hello!

Got an error while running command 'enqueue:consume':

```
Argument 1 passed to Enqueue\Doctrine\DoctrineConnectionFactoryFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /var/www/test/var/cache/dev/ContainerBP8prHE/getEnqueue_Transport_Default_ConnectionFactoryService.php on line 25
```

**How to reproduce**
```console
$ composer create-project symfony/skeleton test
$ cd test
$ composer req enqueue/enqueue-bundle symfony/orm-pack
$ php bin/console enqueue:consume
```

```console
$ composer show
brick/math                           0.9.1   Arbitrary-precision arithmetic library
composer/package-versions-deprecated 1.11.99 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
doctrine/annotations                 1.10.4  Docblock Annotations Parser
doctrine/cache                       1.10.2  PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache,...
doctrine/collections                 1.6.7   PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.0.2   PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on suc...
doctrine/dbal                        2.10.2  Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle             2.1.2   Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  3.0.1   Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   1.4.3   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singula...
doctrine/instantiator                1.3.1   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.0.1   PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for version...
doctrine/orm                         v2.7.3  Object-Relational-Mapper for PHP
doctrine/persistence                 2.0.0   The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mapper...
doctrine/reflection                  1.2.1   The Doctrine Reflection project is a simple library used by the various Doctrine projects which adds some additional funct...
doctrine/sql-formatter               1.1.1   a PHP SQL highlighting library
enqueue/dsn                          0.10.1  Parse DSN
enqueue/enqueue                      0.10.3  Message Queue Library
enqueue/enqueue-bundle               0.10.3  Message Queue Bundle
enqueue/null                         0.10.1  Enqueue Null transport
laminas/laminas-code                 3.4.1   Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.3.0   Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.1.0   Alias legacy ZF class names to Laminas Project equivalents.
ocramius/proxy-manager               2.8.0   A library providing utilities to generate, instantiate and generally operate with Object Proxies
psr/cache                            1.0.1   Common interface for caching libraries
psr/container                        1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0   Standard interfaces for event handling.
psr/log                              1.1.3   Common interface for logging libraries
queue-interop/amqp-interop           0.8.1
queue-interop/queue-interop          0.8.0   Promoting the interoperability of MQs objects. Based on Java JMS
ramsey/collection                    1.1.0   A PHP 7.2+ library for representing and manipulating collections.
ramsey/uuid                          4.1.1   A PHP library for generating and working with universally unique identifiers (UUIDs).
symfony/cache                        v5.1.4  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts              v2.1.3  Generic abstractions related to caching
symfony/config                       v5.1.4  Symfony Config Component
symfony/console                      v5.1.4  Symfony Console Component
symfony/dependency-injection         v5.1.4  Symfony DependencyInjection Component
symfony/deprecation-contracts        v2.1.3  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.1.4  Symfony Doctrine Bridge
symfony/dotenv                       v5.1.4  Registers environment variables from a .env file
symfony/error-handler                v5.1.4  Symfony ErrorHandler Component
symfony/event-dispatcher             v5.1.4  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v2.1.3  Generic abstractions related to dispatching event
symfony/filesystem                   v5.1.4  Symfony Filesystem Component
symfony/finder                       v5.1.4  Symfony Finder Component
symfony/flex                         v1.9.2  Composer plugin for Symfony
symfony/framework-bundle             v5.1.4  Symfony FrameworkBundle
symfony/http-foundation              v5.1.4  Symfony HttpFoundation Component
symfony/http-kernel                  v5.1.4  Symfony HttpKernel Component
symfony/polyfill-intl-grapheme       v1.18.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer     v1.18.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.18.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73               v1.18.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.18.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/routing                      v5.1.4  Symfony Routing Component
symfony/service-contracts            v2.1.3  Generic abstractions related to writing services
symfony/stopwatch                    v5.1.4  Symfony Stopwatch Component
symfony/string                       v5.1.4  Symfony String component
symfony/var-dumper                   v5.1.4  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                 v5.1.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/yaml                         v5.1.4  Symfony Yaml Component
webimpress/safe-writer               2.1.0   Tool to write files safely, to avoid race conditions
```

### PR DESCRIPTION
**Pull request by kdefives**
Fix #1085 - Fix to be compatible with doctrine v3 . Since Doctrine v3, seems some changes with doctrine/common

### CODE REVIEW

**Comment by Steveb-p** [comment]
@kdefives It will probably be fine just replacing the old interface with the new one, but we should probably also add `conflict` to `composer.json` with `doctrine/persistence` versions that did not have it yet. I had a quick look but could not determine since when it was introduced though.

**Comment by kdefives** [comment]
> @kdefives It will probably be fine just replacing the old interface with the new one, but we should probably also add `conflict` to `composer.json` with `doctrine/persistence` versions that did not have it yet. I had a quick look but could not determine since when it was introduced though.

I think it is recent because i started to developed my application 18 days ago and everything worked perfectly until yesterday when i executed a "composer update". Hope it will help you.

**Comment by Steveb-p** [comment]
@kdefives `doctrine/persistence @1.3.0` introduces a compatibility layer (9 months ago):
https://github.com/doctrine/persistence/commit/548f75fc75b421af16cc1d234da02eb6072cdd18

Anything before that will break, because `Doctrine\Persistence\ManagerRegistry` class will not exist. Simple solution would be to mark `doctrine/persistence < 1.3.0` as conflicting.

**Comment by kdefives** [comment]
@Steveb-p Sorry i did not understand what you mean.

When you say _"Simple solution would be to mark doctrine/persistence < 1.3.0 as conflicting."_. Do you mean here : [https://github.com/kdefives/enqueue-dev/blob/patch-1/composer.json](https://github.com/kdefives/enqueue-dev/blob/patch-1/composer.json) ? 
Or in the composer.json of my application? 

Because i tried to add this line in my composer.json of my application but i still have the issue:
```json
"conflict": {
        "symfony/symfony": "*",
        "doctrine/persistence": "<1.3.0"
    },

My application is working perfectly if i change this line
```json
"doctrine/doctrine-bundle": "^2.1",
```
by this line
```json
"doctrine/doctrine-bundle": "v2.1.0",
```

Then, when i execute composer update i can see the downgrade:
```bash
Package operations: 0 installs, 3 updates, 0 removals
  - Downgrading doctrine/persistence (2.0.0 => 1.3.8): Loading from cache
  - Downgrading doctrine/doctrine-bundle (2.1.1 => 2.1.0): Loading from cache
  - Downgrading doctrine/common (3.0.2 => 2.13.3): Loading from cache
```

**Comment by Steveb-p** [comment]
@kdefives I'm specifically saying that switching `DoctrineConnectionFactoryFactory` to use `Doctrine\Persistence\ManagerRegistry` will cause projects that use `doctrine/persistence` lower than 1.3.0 to crash. Because of this we have to either add a compatibility layer (selecting one of the classes to be used as constructor argument depending on which is available) or mark previous versions as being in conflict (editing enqueue's composer.json to say so).

Marking as conflicting is an easy way out of the problem, however providing compatibility layer is a better solution (especially since persistence 1.3 is 9 months old).

**Comment by kdefives** [comment]
I did changes but there are still issues with test classes (as you can see the checks failed). I do not think to have enough time to work on it so if someone can finish this PR, feel free. Moreover, I think it could be useful for other people who starts new Symfony project.

Until new release with this fix, I fixed doctrine-bundle version as explained below, in my project.

Thx again for your help.
Regards

**Comment by nivpenso** [comment]
any news regarding that one?

**Comment by kricha** [comment]
any news?

**Comment by a-menshchikov** [comment]
What news about this PR?

**Comment by nivpenso** [comment]
I have created a follow-up PR (#1105) for this PR. hopefully, it will be merged soon

**Pull request merged**
