### PR TITLE
Order by publish_date within priorities

### PR DESCRIPTION
**Pull request by Gugiman**
When multiple messages got the same priority they should nevertheless be ordered by publish date

### CODE REVIEW

**Comment by makasim** [comment]
Could you please add a func test?

**Comment by makasim** [comment]
@Gugiman Could you please rebase against the latest master.

**Comment by Gugiman** [comment]
Is up-to-date

Unfortunately I'm not familiar with using and writing unit tests.

**Comment by makasim** [comment]
close in favor https://github.com/php-enqueue/enqueue-dev/pull/371

**Pull request closed without merging**
