### PR TITLE
[monitoring] Add support of Datadog

### PR DESCRIPTION
**Pull request by uro**
Pull request for issue #714 

I skipped unit tests of Datadog integration, I think there's nothing to test.

- [x] Implement the integration
- [x] Confirm that it works properly with Datadog
- [x] Confirm that the logic has sense and it's usable for monitoring purposes

### CODE REVIEW

**Comment by makasim** [comment]
This looks awesome!

Could you please add some doc? 

and register it here https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/monitoring/Resources.php#L30

**Comment by uro** [comment]
Documentation added 👍 
https://github.com/uro/enqueue-dev/blob/feature/174-monitoring-datadog-support/docs/monitoring.md#datadog-storage

And as I see, it's already registered in resources.

**Comment by uro** [comment]
@makasim I don't understand why build has failed, I didn't touch stomp or anything. Should I do anything more?

**Comment by makasim** [comment]
available since 0.9.6

**Comment by makasim** [comment]
as for tests, it is not your fault, it fails from time to time.

**Pull request merged**
